// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOPO-46knmNVsn_1SWJDQ-9sTUhw2WMB0',
    appId: '1:320333821419:web:b64602ca6c52a1ae9f55ae',
    messagingSenderId: '320333821419',
    projectId: 'jawda-care',
    authDomain: 'jawda-care.firebaseapp.com',
    storageBucket: 'jawda-care.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqrtMqsr40-vvNjHGRJvSJhLkoAdD8Fkk',
    appId: '1:320333821419:android:9d6e337634c1a9e29f55ae',
    messagingSenderId: '320333821419',
    projectId: 'jawda-care',
    storageBucket: 'jawda-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtcGqLIYv7QFSRlS_D6wheK4A2RkwNpkc',
    appId: '1:320333821419:ios:6da03b8eb1ad0f379f55ae',
    messagingSenderId: '320333821419',
    projectId: 'jawda-care',
    storageBucket: 'jawda-care.firebasestorage.app',
    iosBundleId: 'com.jawdacare.jawdaCare',
  );
}
